---
- hosts:
    - localhost
  tasks:
    - name: Install Required Packages
      become: yes
      apt:
        pkg:
          - bat
          - eza
          - git
          - fish
          - tmux
          - vim
          - curl
          - fzf
          - python3-pip
          - python3-venv
          - libreadline-dev
          - libsqlite3-dev
          - libbz2-dev
          - libffi-dev
          - tig
          - fd-find
          - ripgrep
          - duf
